Update chromatic

diff --git a/bin/chromatic b/bin/chromatic
--- a/bin/chromatic
+++ b/bin/chromatic
@@ -1,209 +1,197 @@
-#!/bin/bash
-
-# A chromium browser updater - https://github.com/pmeinhardt/chromatic-sh
-
-# Configure paths.
-SOURCE="http://commondatastorage.googleapis.com/chromium-browser-snapshots/Mac"
-DESTINATION="/Applications/Chromium.app"
-PLIST="$DESTINATION/Contents/Info.plist"
-TMP="$HOME/Downloads"
-
-# Where to redirect log messages, e.g. /dev/null for quiet mode.
-out=/dev/tty
-
-# Overwrite files and perform restarts without prompting.
-force=
-
-# Print the help text for chromatic.
+#!/usr/bin/env bash
 #
-# Returns nothing.
-help()
-{
-  echo "chromatic [-fhluq]"
-  echo "Options:"
-  echo "  -f    do not prompt before overwriting files and restarting"
-  echo "  -q    be quiet! no status messages on standard out"
-  echo "  -l    log changes since the current revision"
-  echo "  -u    undo last update (requires trashed .app to be present)"
-  echo "  -h    you're looking at it"
+# Updates Chromium on Mac OS X
+#
+# https://github.com/pmeinhardt/chromatic
+
+readonly REPOSITORY="https://commondatastorage.googleapis.com/chromium-browser-snapshots"
+readonly CHANGELOG="http://build.chromium.org/f/chromium/perf/dashboard/ui/changelog.html"
+
+readonly CHROMIUM="/Applications/Chromium.app"
+readonly TRASH="$HOME/.Trash"
+
+log() {
+  local line
+
+  for line in "$@"; do
+    echo "$line"
+  done
 }
 
-# The latest available build revision number.
-latest=""
+err() {
+  local line
 
-# The revision number of the current build.
-current=""
-
-# Logs status messages to the configured output stream.
-#
-# Returns nothing.
-log()
-{
-  echo $(date "+%H:%M:%S ::") $* >> $out
+  for line in "$@"; do
+    echo "$@" >&2
+  done
 }
 
-# Ask to confirm certain actions with a simple Yes or No choice.
-#
-# Example: confirm "Are you sure?"
-# # => will display "Are you sure? [Y/n]" and immediately return after key-down
-#
-# Returns 0 (true) for input 'Y' else 1.
-confirm()
-{
-  read -n 1 -p "$1 [Y/n]" -s && echo
-  test $REPLY = 'Y'
+trash() {
+  local file bname name ext i alt
+
+  for file in "$@"; do
+    bname=$(basename $file)
+    name=${bname//.*}
+    ext=${bname##*.}
+
+    [[ -e "$TRASH/$bname" ]] || mv "$file" $TRASH
+
+    while [[ -e "$file" ]]; do
+      i=$(expr "$i" + 1)
+      alt="$TRASH/$name ($i).$ext"
+      [[ -e "$alt" ]] || mv "$file" "$alt"
+    done
+  done
 }
 
-# Download a remote file to a specified destination on the filesystem.
-#
-# Example: download http://.../chrome-mac.zip ~/Downloads/chrome-mac.zip
-# # => downloads the URLs data into your downloads directory
-#
-# Returns curl's exit status.
-download()
-{
-  curl -L $1 -o $2
+plist() {
+  local buddy plist
+  plist="$CHROMIUM/Contents/Info.plist"
+  buddy="/usr/libexec/PlistBuddy"
+  $buddy -c "Print $1" $plist 2>/dev/null
 }
 
-# Unpacks an archive in its current directory.
-#
-# Example: unpack ~/Downloads/chrome-mac.zip
-# # => unzips the archive's content into ~/Downloads
-#
-# Returns unzip's exit status.
-unpack()
-{
-  unzip -qq $1 -d $(dirname $1)
+help() {
+  log \
+    "Usage: chromatic [command [args]]" \
+    "" \
+    "Commands:" \
+    "  version                  prints the installed version details" \
+    "  info [build number(s)]   opens the changelog (default: installed)" \
+    "  install [build number]   installs a specific build (default: latest)" \
+    "  update                   updates to the most recent build (default)" \
+    "  help                     shows this message"
 }
 
-# Moves a .app to the /Applications folder.
-#
-# Example: install ~/Downloads/Chromium.app
-# # => puts the file into /Applications moving any previous version into Trash
-#
-# Returns nothing.
-install()
-{
-  test -d /Applications/Chromium.app && mv /Applications/Chromium.app ~/.Trash
-  mv $1 /Applications
-}
+version() {
+  local shortver revision
 
-# Undo the last update - requires trashed Chromium.app to be present.
-#
-# Returns 0 (true) on success, an error code otherwise.
-undo()
-{
-  if [ ! -e ~/.Trash/Chromium.app ]; then
-    echo "Could not undo last update"; return 1
+  if [[ ! -d $CHROMIUM ]]; then
+    err "Chromium could not be found at $CHROMIUM"
+    log "You can install it using: chromatic install"
+    return 1
   fi
 
-  rm -rf ~/Applications/Chromium.app
-  mv -f ~/.Trash/Chromium.app /Applications/Chromium.app
+  dispname=$(plist ":CFBundleDisplayName")
+  shortver=$(plist ":CFBundleShortVersionString")
+  revision=$(plist ":SCMRevision")
+
+  log "$dispname $shortver ($revision)"
 }
 
-# Removes temporary files, i.e. those created while updating.
-#
-# Returns nothing.
-cleanup()
-{
-  rm -rf $*
-}
+info() {
+  local min max
 
-# Stop Chromium.
-#
-# Returns nothing.
-stop()
-{
-  if ps -ax | grep -v grep | grep Chromium > /dev/null; then
-    killall TERM Chromium
+  if [[ $# = 2 ]]; then
+    min=$1
+    max=$2
+  elif [[ $# = 1 ]]; then
+    min=$1
+    max=$min
+  elif [[ $# = 0 ]]; then
+    min=$(plist ":SCMRevision")
+    max=$min
   fi
-  while ps -ax | grep -v grep | grep Chromium > /dev/null; do
+
+  open "$CHANGELOG?url=/trunk&mode=html&range=$min:$max"
+}
+
+install() {
+  local dispname shortver revurl current target delta
+  local binurl tmpdir tmpfile rerun
+
+  if [[ -d $CHROMIUM ]]; then
+    dispname=$(plist ":CFBundleDisplayName")
+    shortver=$(plist ":CFBundleShortVersionString")
+    current=$(plist ":SCMRevision")
+  fi
+
+  target="$1"
+
+  if [[ -z "$target" ]]; then
+    revurl="$REPOSITORY/Mac/LAST_CHANGE"
+    target=$(curl -sf $revurl)
+    if [[ $? != 0 ]]; then
+      err "Failed to fetch the latest build number from $revurl"
+      return 1
+    fi
+  fi
+
+  if [[ "$target" = "$current" ]]; then
+    log "Your version of is up to date"
+    return 0
+  fi
+
+  if [[ -n "$current" ]]; then
+    delta=$(expr $target - $current)
+    [[ $delta -lt 0 ]] || delta="+$delta"
+    log "Updating $dispname $shortver ($current) => ($target) $delta"
+  else
+    log "Installing Chromium ($target)"
+  fi
+
+  binurl="$REPOSITORY/Mac/$target/chrome-mac.zip"
+  tmpdir="/tmp/chromatic/$target"
+  tmpfile="$tmpdir/chrome-mac.zip"
+
+  curl -f -# --create-dirs $binurl -o $tmpfile
+  if [[ $? != 0 ]]; then
+    err "Failed to download build $target the from $binurl"
+    return 1
+  fi
+
+  unzip -qq -o $tmpfile -d $tmpdir
+  if [[ $? != 0 ]]; then
+    err "Failed to extract $tmpfile to $tmpdir"
+    return 1
+  fi
+
+  if [[ -d $CHROMIUM ]]; then
+    trash $CHROMIUM
+    if [[ $? != 0 ]]; then
+      err "Failed to remove existing installation"
+      return 1
+    fi
+  fi
+
+  mv "$tmpdir/chrome-mac/Chromium.app" $(dirname $CHROMIUM)
+  if [[ $? != 0 ]]; then
+    err "Failed to install to application directory"
+    return 1
+  fi
+
+  if ps -cax -o command | grep -x Chromium > /dev/null; then
+    killall Chromium
+    rerun=true
+  else
+    rerun=false
+  fi
+
+  while ps -cax -o command | grep -x Chromium > /dev/null; do
     : # wait
   done
+
+  if $rerun; then
+    open $CHROMIUM
+  fi
 }
 
-# Start Chromium.
-#
-# Returns nothing.
-start()
-{
-  open /Applications/Chromium.app
+run() {
+  local command
+
+  command="$1"
+  shift 1
+
+  case "$command" in
+    "help"|"-h"|"--help")   help "$@" ;;
+    "install"|"update"|"")  install "$@" ;;
+    "version")              version "$@" ;;
+    "info")                 info "$@" ;;
+    *)
+      err "Unknown command: $command"
+      help "$@"
+      ;;
+  esac
 }
 
-# Restart Chromium – opened tabs should be restored by the application.
-#
-# Returns nothing.
-restart()
-{
-  stop && start
-}
-
-# Shows the list of changes between 2 given revisions in your default browser.
-#
-# Example: changelog 15734 134482
-# # => opens the list of changes between rev 15734 and 134482
-#
-# Returns nothing.
-changelog()
-{
-  open "http://build.chromium.org/f/chromium/perf/dashboard/ui/changelog.html?url=/trunk/src&mode=html&range=$1:$2"
-}
-
-# Run chromatic with the supplied arguments.
-run()
-{
-  local args=$(getopt "fhluq" $*)
-
-  local changes=
-
-  for arg in $args; do
-    case $arg in
-      -f) force="force";;
-      -q) out=/dev/null;;
-      -l) changes="log";;
-      -u) undo; exit $?;;
-      -h) help && exit 0;;
-    esac
-  done
-
-  latest=$(curl -s $SOURCE/LAST_CHANGE)
-  current=$(/usr/libexec/PlistBuddy -c "Print SCMRevision" $PLIST)
-
-  if [ -z "$latest" ]; then
-    log "Could not retrieve latest revision number" && exit 1
-  fi
-
-  if [ "$latest" = "$current" ]; then
-    log "You're up to date" && exit 0;
-  fi
-
-  log "Latest build version: $latest (+$(expr $latest - $current))"
-
-  if [ -e $TMP/chrome-mac.zip ]; then
-    log "Download file ${TMP}/chrome-mac.zip already exists"
-    [ $force ] || confirm "Continue anyway?" || exit 0
-  fi
-
-  log "Downloading latest build"
-  if ! download $SOURCE/$latest/chrome-mac.zip $TMP/chrome-mac.zip; then
-    log "Download failed" && exit 1
-  fi
-
-  log "Unzipping downloaded build"
-  if ! unpack $TMP/chrome-mac.zip; then
-    log "Unzipping archive failed" && exit 1
-  fi
-
-  log "Installing to Applications folder"
-  install $TMP/chrome-mac/Chromium.app
-
-  log "Cleaning up temporary files from $TMP"
-  cleanup $TMP/chrome-mac.zip $TMP/chrome-mac
-
-  if [ $force ] || confirm "Restart?"; then restart; fi
-
-  if [ $changes ]; then changelog $current $latest; fi
-}
-
-# And go...
-run $*
+run "$@"
